plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rahimshop.admin'
    compileSdk 35

    defaultConfig {
        applicationId "com.rahimshop.admin"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
